### ISSUE TITLE
rosdep install problem

### ISSUE THREAD

**Issue by dashuaip** [XieShaosong/aubo_robot_ros2#3]
我在这一步遇到了找不到包的问题，麻烦作者帮忙看一下
I encountered the problem of not being able to find the package at this step. Could you please help me take a look？

ros2@ubuntu:~/aubo_ros2_ws$ rosdep install --from-paths src --ignore-src --rosdistro foxy -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
aubo_ros2_moveit_config: Cannot locate rosdep definition for [warehouse_ros_mongo]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

![图片](https://github.com/XieShaosong/aubo_robot_ros2/assets/130347165/0fd32d9d-87bf-40d3-abcc-a0d7928270cc)

**Comment by dashuaip** [comment]
我用的是ubuntu 20.04 + ros2 foxy。
I am using ubuntu 20.04+ros2 foxy.

**Comment by XieShaosong** [comment]
You can try to manually install `sudo apt install ros-foxy-warehouse-ros-mongo`

**Comment by dashuaip** [comment]
> 

Thank you. It's useful.
