### ISSUE TITLE
No transform from [***] to [base_link]

### ISSUE THREAD

**Issue by dashuaip** [XieShaosong/aubo_robot_ros2#4]
当我在终端中运行`ros2 launch aubo_ros2_moveit_config aubo_moveit.launch.py robot_ip:=127.0.0.1`
发生了坐标转换关系的错误，请问应该怎么解决？

When I was running `ros2 launch aubo_ros2_moveit_config aubo_moveit.launch.py robot_ip:=127.0.0.1` on the terminal, an error occurred in coordinate conversion. What should I do to resolve it?

![图片](https://github.com/XieShaosong/aubo_robot_ros2/assets/130347165/078ee250-28c1-4dc3-b78f-5ee76fa91210)

**Comment by dashuaip** [comment]
Such as, 
No transform from [foreArm_Link] to [base_link],
No transform from [shoulder_Link] to [base_link],
No transform from [upperArm_Link] to [base_link],
No transform from [wrist1_Link] to [base_link],
No transform from [wrist2_Link] to [base_link],
No transform from [wrist3_Link] to [base_link].

**Comment by XieShaosong** [comment]
simulation ： 
ros2 launch  aubo_ros2_moveit_config aubo_moveit_sim.launch.py

**Comment by XieShaosong** [comment]
你有机械臂么？

**Comment by dashuaip** [comment]
> simulation ： ros2 launch aubo_ros2_moveit_config aubo_moveit_sim.launch.py

这个虽然转换没问题，但是执行失败了。我目前使用的是虚拟机。
Although the conversion was fine, the execution failed. And I am currently using a virtual machine.

![图片](https://github.com/XieShaosong/aubo_robot_ros2/assets/130347165/c4643872-6c56-4ad0-9e9a-a14c6a97a1fe)

![图片](https://github.com/XieShaosong/aubo_robot_ros2/assets/130347165/02fbaf28-e275-48be-97da-aac7dcb7bbf5)

**Comment by XieShaosong** [comment]
simulation 只能plan， 不能执行的。

**Comment by dashuaip** [comment]
> 你有机械臂么？

我有aubo_i10的机械臂，如果这个i5的成功运行的话，后面再修改成i10的做实验。
但是目前用虚拟机仿真报错，真实的也控制不了吧。
I have a aubo_i10 robotic arm. If this i5 runs successfully, I will modify it to i10 for experimentation later.
But currently, using virtual machine simulation to report errors cannot control the real situation.

**Comment by XieShaosong** [comment]
我这边只有aubo i5, 在i5上能成功plan、execute。aubo i10 替换urdf 相关内容就行了

**Comment by dashuaip** [comment]
> simulation 只能plan， 不能执行的。

刚刚试了一下，的确如此o(￣▽￣)ｄ。
但是后面我想用moveit2控制真实的 aubo_i10 机械臂，还是需要用到您的 aubo_moveit.launch.py 文件。
Just gave it a try, and it's true.
But later on, I want to use moveit2 to control the real aubo_ I10 robotic arm, still requires your aubo_ Moveit.launch.py file.

**Comment by dashuaip** [comment]
> 我这边只有aubo i5, 在i5上能成功plan、execute。aubo i10 替换urdf 相关内容就行了

那么你在使用ros2 launch aubo_ros2_moveit_config aubo_moveit.launch.py robot_ip:=192.168.1.*
控制aubo_i5的时候，moveit界面有提示转换关系错误的情况吗？
因为我学习使用ros1控制的时候，ip改成127.0.0.1也能成功运行，不会有报错的情况，所以就套用了进来

![图片](https://github.com/XieShaosong/aubo_robot_ros2/assets/130347165/8c49c4e9-f205-4e12-8510-4dd69f4fed36)

**Comment by dashuaip** [comment]
目前还在代码实验的阶段，还没有更换模型，所以这是在使用您提供的i5模型运行时出现的情况。
At present, it is still in the stage of code experimentation and the model has not been replaced, so this is a situation that occurred when running with the i5 model you provided.

**Comment by XieShaosong** [comment]
报错是因为没有机械臂aubo ros2 driver不会启动， 就没有发布关节角度。 simulation 就会通过joint_state_publisher 发布一个[0,0,0,0,0,0]的关节角度。

**Comment by dashuaip** [comment]
> 报错是因为没有机械臂aubo ros2 driver不会启动， 就没有发布关节角度。 simulation 就会通过joint_state_publisher 发布一个[0,0,0,0,0,0]的关节角度。

明白了，所以这个代码目前还不能用于127.0.0.1虚拟机械臂的 plan & execute 实验。那么修改成 i10 的模型及参数后， 连接上真实的机械臂，这个转换关系的错误会解决吗？
I understand, so this code cannot currently be used for the plan&execute experiment of 127.0.0.1 virtual robotic arm. Will the error in the conversion relationship be resolved when the model and parameters of i10 are modified and connected to a real robotic arm?

**Comment by XieShaosong** [comment]
> > 报错是因为没有机械臂aubo ros2 driver不会启动， 就没有发布关节角度。 simulation 就会通过joint_state_publisher 发布一个[0,0,0,0,0,0]的关节角度。
> 
> 明白了，所以这个代码目前还不能用于127.0.0.1虚拟机械臂的 plan & execute 实验。那么修改成 i10 的模型及参数后， 连接上真实的机械臂，这个转换关系的错误会解决吗？ I understand, so this code cannot currently be used for the plan&execute experiment of 127.0.0.1 virtual robotic arm. Will the error in the conversion relationship be resolved when the model and parameters of i10 are modified and connected to a real robotic arm?

我连aubo i5是没问题， i10我并不知道。并且我没用aubo提供的虚拟机。

**Comment by dashuaip** [comment]
好的谢谢，我修改成 i10 的模型实机实验一下。
Okay, thank you. I will modify it to an i10 model for real machine experiments.
