### ISSUE TITLE
请问你的原来的aubo机械臂的ros1的包是在哪里下载的？

### ISSUE THREAD

**Issue by dashuaip** [XieShaosong/aubo_robot_ros2#5]
我看官网给的头文件serviceinterface.h没有你的函数多，比如我需要的这个robotServiceEnterRobotReduceMode()，
进入缩减模式的函数就没有。请问能不能提供一下原来ros1版本的整个工作空间的包或者来源？

**Comment by XieShaosong** [comment]
https://github.com/AuboRobot/aubo_robot

**Comment by dashuaip** [comment]
他官网这个包的ros_driver没有你ros2的这个新啊，比如就没有robotServiceEnterRobotReduceMode()函数，而且也不是libauborobotcontroller.so.2.0的库。或者说你是下的哪一个版本呢？Noetic还是Melodic

**Comment by XieShaosong** [comment]
可以找aubo售后人员要最新的sdk。

**Comment by dashuaip** [comment]
好的谢谢
